export const FIND_BATCH_RESULT = 'FIND_BATCH_RESULT';
export const BATCH_RESULT_SUCCESS = 'BATCH_RESULT_SUCCESS';
export const BATCH_RESULT_ERROR = 'BATCH_RESULT_ERROR';
export const BATCH_RESULT_LOADING = 'BATCH_RESULT_LOADING';
